### ISSUE TITLE
Object.entries is not a function un backup

### ISSUE THREAD

**Issue by MaxiTalenti** [dalenguyen/firebase-functions-helper#14]
Hi, when i call this line:

firebaseHelper.firestore.backup(firestoreInstance, 'Categories', 'Subcollection')

appear this error:

```
TypeError: Object.entries is not a function
    at FirestoreHelper.<anonymous> (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:268:47)
    at next (native)
    at /user_code/node_modules/firebase-functions-helper/dist/firestore.js:7:71
    at __awaiter (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:3:12)
    at FirestoreHelper.getSubCollection (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:267:16)
    at results.then.dt (/user_code/node_modules/firebase-functions-helper/dist/firestore.js:244:26)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by dalenguyen** [comment]
Hi @MaxiTalenti, which version of Node are you using? Can you try to update it to v8 or v10?

**Comment by MaxiTalenti** [comment]
> Hi @MaxiTalenti, which version of Node are you using? Can you try to update it to v8 or v10?

Hi @dalenguyen, update to v8 and work fine, thanks you!
